// app/layout.tsx
import type { Metadata } from "next";
import Providers from "@/providers/query-provider";

import "./globals.css";
import NotificationProvider from "@/components/notificationProvider";
import { SessionProvider } from "next-auth/react";
import ChatListener from "@/components/chat-listner";

export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
  icons: "/logo.png",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Russo+One&display=swap"
          rel="stylesheet"
        />
      </head>

      <body>
        <SessionProvider >
          <Providers>
            <ChatListener />
            <NotificationProvider />
            {children}
          </Providers>
        </SessionProvider>
      </body>
    </html>
  );
}

// import type { Metadata } from "next";
// import Providers from "@/providers/query-provider";
// import "./globals.css";

// export const metadata: Metadata = {
//   title: "Home",
//   description: "Generated by create next app",
//   icons: "/logo.png"
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en" suppressHydrationWarning>
//       <body>
//         <Providers>
//           {children}
//         </Providers>
//       </body>
//     </html>
//   );
// }
